// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: master-worker.proto

#include "master-worker.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace masterworker {
class FilenameDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Filename>
      _instance;
} _Filename_default_instance_;
class FilenamesDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Filenames>
      _instance;
} _Filenames_default_instance_;
}  // namespace masterworker
namespace protobuf_master_2dworker_2eproto {
static void InitDefaultsFilename() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::masterworker::_Filename_default_instance_;
    new (ptr) ::masterworker::Filename();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::masterworker::Filename::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Filename =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFilename}, {}};

static void InitDefaultsFilenames() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::masterworker::_Filenames_default_instance_;
    new (ptr) ::masterworker::Filenames();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::masterworker::Filenames::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Filenames =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsFilenames}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Filename.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Filenames.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::Filename, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::Filename, filename_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::Filenames, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::masterworker::Filenames, filenames_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::masterworker::Filename)},
  { 6, -1, sizeof(::masterworker::Filenames)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::masterworker::_Filename_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::masterworker::_Filenames_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "master-worker.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\023master-worker.proto\022\014masterworker\"\034\n\010F"
      "ilename\022\020\n\010filename\030\001 \001(\t\"\036\n\tFilenames\022\021"
      "\n\tfilenames\030\001 \001(\t2\214\001\n\006Worker\022\?\n\013StartMap"
      "per\022\026.masterworker.Filename\032\026.masterwork"
      "er.Filename\"\000\022A\n\014StartReducer\022\027.masterwo"
      "rker.Filenames\032\026.masterworker.Filename\"\000"
      "B6\n\033io.grpc.examples.helloworldB\017HelloWo"
      "rldProtoP\001\242\002\003HLWb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 304);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "master-worker.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_master_2dworker_2eproto
namespace masterworker {

// ===================================================================

void Filename::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Filename::kFilenameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Filename::Filename()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_master_2dworker_2eproto::scc_info_Filename.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:masterworker.Filename)
}
Filename::Filename(const Filename& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  filename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.filename().size() > 0) {
    filename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filename_);
  }
  // @@protoc_insertion_point(copy_constructor:masterworker.Filename)
}

void Filename::SharedCtor() {
  filename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Filename::~Filename() {
  // @@protoc_insertion_point(destructor:masterworker.Filename)
  SharedDtor();
}

void Filename::SharedDtor() {
  filename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Filename::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Filename::descriptor() {
  ::protobuf_master_2dworker_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_master_2dworker_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Filename& Filename::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_master_2dworker_2eproto::scc_info_Filename.base);
  return *internal_default_instance();
}


void Filename::Clear() {
// @@protoc_insertion_point(message_clear_start:masterworker.Filename)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Filename::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:masterworker.Filename)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string filename = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->filename().data(), static_cast<int>(this->filename().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "masterworker.Filename.filename"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:masterworker.Filename)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:masterworker.Filename)
  return false;
#undef DO_
}

void Filename::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:masterworker.Filename)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string filename = 1;
  if (this->filename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->filename().data(), static_cast<int>(this->filename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.Filename.filename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->filename(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:masterworker.Filename)
}

::google::protobuf::uint8* Filename::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:masterworker.Filename)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string filename = 1;
  if (this->filename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->filename().data(), static_cast<int>(this->filename().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.Filename.filename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->filename(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterworker.Filename)
  return target;
}

size_t Filename::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterworker.Filename)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string filename = 1;
  if (this->filename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->filename());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Filename::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:masterworker.Filename)
  GOOGLE_DCHECK_NE(&from, this);
  const Filename* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Filename>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:masterworker.Filename)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:masterworker.Filename)
    MergeFrom(*source);
  }
}

void Filename::MergeFrom(const Filename& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:masterworker.Filename)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.filename().size() > 0) {

    filename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filename_);
  }
}

void Filename::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:masterworker.Filename)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Filename::CopyFrom(const Filename& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterworker.Filename)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Filename::IsInitialized() const {
  return true;
}

void Filename::Swap(Filename* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Filename::InternalSwap(Filename* other) {
  using std::swap;
  filename_.Swap(&other->filename_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Filename::GetMetadata() const {
  protobuf_master_2dworker_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_master_2dworker_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Filenames::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Filenames::kFilenamesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Filenames::Filenames()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_master_2dworker_2eproto::scc_info_Filenames.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:masterworker.Filenames)
}
Filenames::Filenames(const Filenames& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  filenames_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.filenames().size() > 0) {
    filenames_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filenames_);
  }
  // @@protoc_insertion_point(copy_constructor:masterworker.Filenames)
}

void Filenames::SharedCtor() {
  filenames_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Filenames::~Filenames() {
  // @@protoc_insertion_point(destructor:masterworker.Filenames)
  SharedDtor();
}

void Filenames::SharedDtor() {
  filenames_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Filenames::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Filenames::descriptor() {
  ::protobuf_master_2dworker_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_master_2dworker_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Filenames& Filenames::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_master_2dworker_2eproto::scc_info_Filenames.base);
  return *internal_default_instance();
}


void Filenames::Clear() {
// @@protoc_insertion_point(message_clear_start:masterworker.Filenames)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  filenames_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Filenames::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:masterworker.Filenames)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string filenames = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filenames()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->filenames().data(), static_cast<int>(this->filenames().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "masterworker.Filenames.filenames"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:masterworker.Filenames)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:masterworker.Filenames)
  return false;
#undef DO_
}

void Filenames::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:masterworker.Filenames)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string filenames = 1;
  if (this->filenames().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->filenames().data(), static_cast<int>(this->filenames().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.Filenames.filenames");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->filenames(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:masterworker.Filenames)
}

::google::protobuf::uint8* Filenames::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:masterworker.Filenames)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string filenames = 1;
  if (this->filenames().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->filenames().data(), static_cast<int>(this->filenames().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "masterworker.Filenames.filenames");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->filenames(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:masterworker.Filenames)
  return target;
}

size_t Filenames::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:masterworker.Filenames)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string filenames = 1;
  if (this->filenames().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->filenames());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Filenames::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:masterworker.Filenames)
  GOOGLE_DCHECK_NE(&from, this);
  const Filenames* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Filenames>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:masterworker.Filenames)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:masterworker.Filenames)
    MergeFrom(*source);
  }
}

void Filenames::MergeFrom(const Filenames& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:masterworker.Filenames)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.filenames().size() > 0) {

    filenames_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filenames_);
  }
}

void Filenames::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:masterworker.Filenames)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Filenames::CopyFrom(const Filenames& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:masterworker.Filenames)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Filenames::IsInitialized() const {
  return true;
}

void Filenames::Swap(Filenames* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Filenames::InternalSwap(Filenames* other) {
  using std::swap;
  filenames_.Swap(&other->filenames_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Filenames::GetMetadata() const {
  protobuf_master_2dworker_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_master_2dworker_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace masterworker
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::masterworker::Filename* Arena::CreateMaybeMessage< ::masterworker::Filename >(Arena* arena) {
  return Arena::CreateInternal< ::masterworker::Filename >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::masterworker::Filenames* Arena::CreateMaybeMessage< ::masterworker::Filenames >(Arena* arena) {
  return Arena::CreateInternal< ::masterworker::Filenames >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
